name: vamos_cartographie
description: "Cartographie api for vamos project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stored_file_application:
    path: ../../packages/stored_file_application
  map_application:
    path: ../../packages/map_application
  domain_core:
    path: ../../packages/domain_core
  trip_application:
    path: ../../packages/trip_application
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  flutter_map_dragmarker: ^8.0.3
  flutter_map_line_editor: ^8.0.0
  image_picker: ^1.2.2
  file_selector: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.8
  ferry: ^0.16.1+2
  update: ^0.4.0
  gql_tristate_value: ^1.1.0
  dio: ^5.9.2
  path: ^1.9.1
  riverpod: ^3.2.1
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  http: ^1.6.0
  gql_http_link: ^1.2.0
  built_value: ^8.12.6
  ferry_exec: ^0.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  gql_exec: ^1.1.1-alpha+1699813812660
  gql_link: ^1.1.0
  uuid: ^4.5.3

dev_dependencies:
  test: ^1.30.0
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  ferry_generator2: ^0.1.0-dev.5
  lints: ^6.1.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
