name: vamos_frontend_workspace
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - apps/vamos_cartographie
  - packages/domain_core
  - packages/map_application
  - packages/media_application
  - packages/trip_application

dev_dependencies:
  melos: ^7.0.0

melos:
  scripts:
    analyze:
      run: melos exec -- dart analyze .
    test:
      run: melos exec --dir-exists=test -- dart test

    # Génère pour TOUS les packages éligibles d'un coup
    generate:all:
      run: melos exec --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
      description: Lance build_runner sur tous les packages compatibles

    # Te demande de CHOISIR le package dans une liste
    generate:
      run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
      description: Choisir un package spécifique pour lancer build_runner
      select-package:
        depends-on: "build_runner"
