"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

"""Indicates an Input Object is a OneOf Input Object."""
directive @oneOf on INPUT_OBJECT

"""Date (isoformat)"""
scalar Date

input LatLngInput {
  lat: Float!
  lng: Float!
}

type LatLngType {
  lat: Float!
  lng: Float!
}

type Mutation {
  createTrip(trip: TripInput!): TripType!
  updateTrip(id: ID!, trip: TripInput!): TripType!
  deleteTrip(id: ID!): ID!
  generateImageUploadUrl(extension: String!): UploadConfig!
  confirmImageUpload(fileKey: String!): UploadConfirmation!
}

type Query {
  trip(id: ID!): TripType
  trips: [TripType!]!
}

input SegmentInput {
  type: SegmentTypeEnum!
  intermediatePoints: [LatLngInput!]!
}

type SegmentType {
  id: ID!
  type: SegmentTypeEnum!
  intermediatePoints: [LatLngType!]!
}

enum SegmentTypeEnum {
  bike
  car
  boat
  walk
  train
}

input TripInput {
  title: String!
  description: String!
  date: Date
  imageUrls: [String!]
  waypoints: [WaypointInput!]
  segments: [SegmentInput!]
}

type TripType {
  id: ID!
  title: String!
  description: String!
  date: Date
  imageUrls: [String!]!
  waypoints: [WaypointType!]!
  segments: [SegmentType!]!
}

type UploadConfig {
  uploadUrl: String!
  fileKey: String!
}

type UploadConfirmation {
  urlLink: String!
}

input WaypointInput {
  lat: Float!
  lng: Float!
  type: WaypointTypeEnum!
  description: String
  imageUrls: [String!]
}

type WaypointType {
  id: ID!
  lat: Float!
  lng: Float!
  description: String!
  imageUrls: [String!]!
  type: WaypointTypeEnum!
}

enum WaypointTypeEnum {
  start
  end
  waypoint
  water
  food
  repair
  shelter
  camping
  viewpoint
  historic
  beach
  boat
  warning
}

