"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

"""Indicates an Input Object is a OneOf Input Object."""
directive @oneOf on INPUT_OBJECT

"""Date (isoformat)"""
scalar Date

input ImageInput {
  fileKey: String!
}

type ImageType {
  fileKey: String!
  url: String!
}

input LatLngInput {
  lat: Float!
  lng: Float!
}

type LatLngType {
  lat: Float!
  lng: Float!
}

type Mutation {
  createTrip(trip: TripInput!): TripType!
  deleteTrip(input: TripDeleteInput!): TripType!
  attachImageToTrip(tripId: Int!, fileKey: String!): TripImageType!
  updateTrip(id: Int!, trip: TripUpdateInput!): TripType!
  createImage(data: ImageInput!): ImageType!
  generateImageUploadUrl(extension: String!): UploadConfig!
}

type Query {
  trips: [TripType!]!
  trip(id: Int!): TripType!
}

input SegmentInput {
  type: SegmentTypeEnum!
  intermediatePoints: [LatLngInput!]!
}

type SegmentType {
  type: SegmentTypeEnum!
  intermediatePoints: [LatLngType!]!
}

enum SegmentTypeEnum {
  bike
  car
  boat
  walk
  train
}

input TripDeleteInput {
  id: Int!
}

type TripImageType {
  image: ImageType!
  order: Int!
}

input TripInput {
  title: String!
  description: String
  date: Date
  waypoints: [WaypointInput!] = null
  segments: [SegmentInput!] = null
}

type TripType {
  id: Int!
  title: String!
  description: String!
  date: Date
  images: [TripImageType!]!
  waypoints: [WaypointType!]!
  segments: [SegmentType!]!
}

input TripUpdateInput {
  title: String
  description: String
  date: Date
  waypoints: [WaypointInput!] = null
  segments: [SegmentInput!] = null
}

type UploadConfig {
  uploadUrl: String!
  fileKey: String!
}

type WaypointImageType {
  image: ImageType!
  order: Int!
}

input WaypointInput {
  lat: Float!
  lng: Float!
  type: WaypointTypeEnum!
  title: String
  description: String
}

type WaypointType {
  id: ID!
  lat: Float!
  lng: Float!
  title: String!
  description: String!
  images: [WaypointImageType!]!
  type: WaypointTypeEnum!
}

enum WaypointTypeEnum {
  start
  end
  waypoint
  water
  food
  repair
  shelter
  camping
  viewpoint
  historic
  beach
  boat
  warning
}

