#import "../../waypoints/fragments/waypoint_fields.graphql"
#import "../fragments/trip_fields.graphql"
#import "../../media/fragments/image_fields.graphql"
#import "../../segments/fragments/segment_fields.graphql"
mutation CreateTrip($trip: TripInput!) {
    createTrip(trip: $trip) {
        ...TripFields
    }
}

mutation UpdateTrip($trip: TripUpdateInput!, $id: Int!) {
    updateTrip(trip: $trip, id: $id) {
        ...TripFields
    }
}

mutation DeleteTrip($id: Int!) {
    deleteTrip(id: $id)
}
mutation DeleteImageFromTrip($tripId: Int!, $fileKey: String!) {
    deleteImageFromTrip(tripId: $tripId, fileKey: $fileKey)
}
mutation AttachImageToTrip($tripId: Int!, $fileKey: String!) {
    attachImageToTrip(tripId: $tripId, fileKey: $fileKey) {
        image {
            ...ImageFields
        }
    }
}
