"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

"""Indicates an Input Object is a OneOf Input Object."""
directive @oneOf on INPUT_OBJECT

"""Date (isoformat)"""
scalar Date

input LatLngInput {
  lat: Float!
  lng: Float!
}

type LatLngType {
  lat: Float!
  lng: Float!
}

input MediaImageInput {
  fileKey: String!
}

type MediaImageType {
  fileKey: String!
  url: String!
}

type Mutation {
  createTrip(trip: TripInput!): TripType!
  attachImageToTrip(tripId: Int!, fileKey: String!): TripImageType!
  updateTrip(id: Int!, trip: TripUpdateInput!): TripType!
  deleteImageFromTrip(tripId: Int!, fileKey: String!): String!
  deleteTrip(id: Int!): Boolean!
  createImage(data: MediaImageInput!): MediaImageType!
  generateImageUploadUrl(extension: String!): UploadConfig!
  attachImageToWaypoint(waypointId: Int!, fileKey: String!): WaypointImageType!
  deleteImageFromWaypoint(waypointId: Int!, fileKey: String!): String!
  updateWaypoint(id: Int!, waypoint: WaypointUpdateInput!): WaypointType!
  createWaypoint(tripId: Int!, waypoint: WaypointCreateInput!): WaypointType!
  deleteWaypoint(id: Int!): Boolean!
  updateSegment(id: Int!, segment: SegmentUpdateInput!): SegmentType!
  createSegment(tripId: Int!, segment: SegmentCreateInput!): SegmentType!
  deleteSegment(id: Int!): Boolean!
}

type Query {
  trips: [TripType!]!
  trip(id: Int!): TripType!
}

input SegmentCreateInput {
  type: SegmentTypeEnum!
  startWaypointId: Int!
  endWaypointId: Int!
  intermediatePoints: [LatLngInput!]! = []
}

type SegmentType {
  id: Int!
  type: SegmentTypeEnum!
  startWaypoint: WaypointType!
  endWaypoint: WaypointType!
  intermediatePoints: [LatLngType!]!
}

enum SegmentTypeEnum {
  bike
  car
  boat
  walk
  train
}

input SegmentUpdateInput {
  type: SegmentTypeEnum
  startWaypointId: Int
  endWaypointId: Int
  intermediatePoints: [LatLngInput!]
}

type TripImageType {
  image: MediaImageType!
  order: Int!
}

input TripInput {
  title: String!
  description: String
  date: Date
}

type TripType {
  id: Int!
  title: String!
  description: String!
  date: Date
  images: [TripImageType!]!
  waypoints: [WaypointType!]!
  segments: [SegmentType!]!
}

input TripUpdateInput {
  title: String
  description: String
  date: Date
}

type UploadConfig {
  uploadUrl: String!
  fileKey: String!
}

input WaypointCreateInput {
  lat: Float!
  lng: Float!
  type: WaypointEnum!
  title: String = null
  description: String = null
}

enum WaypointEnum {
  START
  END
  WAYPOINT
  WATER
  FOOD
  REPAIR
  SHELTER
  CAMPING
  VIEWPOINT
  HISTORIC
  BEACH
  BOAT
  WARNING
}

type WaypointImageType {
  image: MediaImageType!
  order: Int!
}

type WaypointType {
  id: Int!
  lat: Float!
  lng: Float!
  title: String!
  description: String!
  images: [WaypointImageType!]!
  type: WaypointEnum!
}

input WaypointUpdateInput {
  lat: Float
  lng: Float
  title: String
  type: WaypointEnum
  description: String
}

