"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

"""Indicates an Input Object is a OneOf Input Object."""
directive @oneOf on INPUT_OBJECT

type CreateWaypointPayload {
  waypoint: WaypointType!
  vertex: VertexType!
}

"""Date (isoformat)"""
scalar Date

type InsertVertexToSegmentPayload {
  segmentLeft: SegmentType!
  segmentRight: SegmentType!
}

input LatLngInput {
  lat: Float!
  lng: Float!
}

type LatLngType {
  lat: Float!
  lng: Float!
}

input MediaImageInput {
  fileKey: String!
}

type MediaImageType {
  fileKey: String!
  url: String!
}

enum MobilityType {
  BIKE
  CAR
  BOAT
  WALK
  TRAIN
}

type Mutation {
  createTrip(trip: TripInput!): TripType!
  attachImageToTrip(tripId: Int!, fileKey: String!): TripImageType!
  updateTrip(id: Int!, trip: TripUpdateInput!): TripType!
  deleteImageFromTrip(tripId: Int!, fileKey: String!): String!
  deleteTrip(id: Int!): Boolean!
  createImage(data: MediaImageInput!): MediaImageType!
  generateImageUploadUrl(extension: String!): UploadConfig!
  attachImageToWaypoint(waypointId: Int!, fileKey: String!): WaypointImageType!
  deleteImageFromWaypoint(waypointId: Int!, fileKey: String!): String!
  updateWaypoint(id: Int!, input: WaypointUpdateInput!): WaypointType!
  createWaypoint(tripId: Int!, input: WaypointCreateInput!): CreateWaypointPayload!
  deleteWaypoint(id: Int!): Boolean!
  insertVertexToSegment(vertexId: Int!, segmentId: Int!): InsertVertexToSegmentPayload!
  updateSegment(id: Int!, input: SegmentUpdateInput!): SegmentType!
  createSegment(tripId: Int!, input: SegmentCreateInput!): SegmentType!
  deleteSegment(id: Int!): Boolean!
  moveVertex(id: Int!, latLng: LatLngInput!): VertexType!
  createVertex(tripId: Int!, latLng: LatLngInput!): VertexType!
  deleteVertex(id: Int!): Boolean!
}

enum PoiCategory {
  START
  END
  WAYPOINT
  WATER
  FOOD
  REPAIR
  SHELTER
  CAMPING
  VIEWPOINT
  HISTORIC
  BEACH
  BOAT
  WARNING
}

type Query {
  trips: [TripType!]!
  trip(id: Int!): TripType!
}

input SegmentCreateInput {
  mobilityType: MobilityType!
  startVertexId: Int!
  endVertexId: Int!
}

type SegmentType {
  id: Int!
  mobilityType: MobilityType!
  startVertex: VertexType!
  endVertex: VertexType!
  geometry: [LatLngType!]!
}

input SegmentUpdateInput {
  mobilityType: MobilityType
  startVertexId: Int
  endVertexId: Int
}

type TopologyType {
  vertices: [VertexType!]!
  segments: [SegmentType!]!
}

type TripImageType {
  image: MediaImageType!
  order: Int!
}

input TripInput {
  title: String!
  description: String
  date: Date
}

type TripType {
  id: Int!
  title: String!
  description: String!
  date: Date
  images: [TripImageType!]!
  waypoints: [WaypointType!]!
  topology: TopologyType!
}

input TripUpdateInput {
  title: String
  description: String
  date: Date
}

type UploadConfig {
  uploadUrl: String!
  fileKey: String!
}

type VertexType {
  id: Int!
  latLng: LatLngType!
}

input WaypointCreateInput {
  poiCategory: PoiCategory!
  title: String = null
  description: String = null
  vertexId: Int = null
  latLng: LatLngInput = null
}

type WaypointImageType {
  image: MediaImageType!
  order: Int!
}

type WaypointType {
  id: Int!
  title: String!
  description: String!
  images: [WaypointImageType!]!
  poiCategory: PoiCategory!
  vertex: VertexType!
}

input WaypointUpdateInput {
  title: String
  poiCategory: PoiCategory
  vertexId: Int
  description: String
}

