#import "../fragments/trip.graphql"
mutation CreateTrip($trip: TripInput!) {
    createTrip(trip: $trip) {
        ...TripFields
        waypoints {
            ...WaypointFields
        }
        segments {
            ...SegmentFields
        }
    }
}

mutation UpdateTrip($id: ID!, $trip: TripInput!) {
    updateTrip(id: $id, trip: $trip) {
        ...TripFields
        waypoints {
            ...WaypointFields
        }
        segments {
            ...SegmentFields
        }
    }
}

mutation DeleteTrip($id: ID!) {
    deleteTrip(id: $id)
}
