#import "../fragments/trip.graphql"
mutation CreateTrip($trip: TripInput!) {
    createTrip(trip: $trip) {
        ...TripFields
        waypoints {
            ...WaypointFields
        }
        segments {
            ...SegmentFields
        }
    }
}

mutation UpdateTrip($trip: TripUpdateInput!, $id: Int!) {
    updateTrip(trip: $trip, id: $id) {
        ...TripFields
        waypoints {
            ...WaypointFields
        }
        segments {
            ...SegmentFields
        }
    }
}

mutation DeleteTrip($id: Int!) {
    deleteTrip(input: { id: $id }) {
        id
    }
}
