#import "waypoint_fields.graphql"
#import "../media/image_fields.graphql"
mutation UpdateWaypoint($id: Int!, $waypoint: WaypointUpdateInput!) {
    updateWaypoint(input: $waypoint, id: $id) {
        ...WaypointFields
    }
}
mutation CreateBlankWaypointFromPosition($tripId: Int!, $latLng: LatLngInput!) {
    createBlankWaypointFromPosition(tripId: $tripId, latLng: $latLng) {
        ...CreateWaypointPayloadFields
    }
}

mutation CreateBlankWaypointFromVertex($tripId: Int!, $vertexId: Int!) {
    createBlankWaypointFromVertex(tripId: $tripId, vertexId: $vertexId) {
        ...CreateWaypointPayloadFields
    }
}

mutation DeleteWaypoint($waypointId: Int!) {
    deleteWaypoint(id: $waypointId)
}
