#import "../../waypoints/fragments/waypoint_fields.graphql"
#import "../fragments/trip_fields.graphql"
#import "../../topology/segments/fragments/segment_fields.graphql"
#import "../../topology/vertex/vertex_fields.graphql"

query GetAllTrips {
    trips {
        ...TripFields
    }
}

query GetTrip($id: Int!) {
    trip(id: $id) {
        ...TripFields
        waypoints {
            ...WaypointFields
        }
        topology {
            vertices {
                ...VertexFields
            }
            segments {
                ...SegmentFields
            }
        }
    }
}
