#import "vertex_fields.graphql"

fragment SegmentFields on SegmentType {
    id
    mobilityType
    startVertex {
        ...VertexFields
    }
    endVertex {
        ...VertexFields
    }
    geometry {
        ...LatLngFields
    }
}
fragment SegmentMergePayloadFragment on SegmentMergePayload {
    deletedSegmentIds
    segment {
        ...SegmentFields
    }
}

mutation MergeSegment($tripId: UUID!, $input: SegmentMergeInput!) {
    mergeSegments(tripId: $tripId, input: $input) {
        ...SegmentMergePayloadFragment
    }
}
