enum PoiCategory {
  start,
  end,
  waypoint,
  water,
  food,
  repair,
  shelter,
  camping,
  viewpoint,
  historic,
  beach,
  boat,
  warning,
  other,

  // @override
  // String get label => switch (this) {
  //   PoiCategory.start => 'Départ',
  //   PoiCategory.end => 'Arrivée',
  //   PoiCategory.waypoint => 'Point de passage',
  //   PoiCategory.water => 'Point d\'eau',
  //   PoiCategory.food => 'Ravitaillement',
  //   PoiCategory.repair => 'Réparation vélo',
  //   PoiCategory.shelter => 'Abri',
  //   PoiCategory.camping => 'Camping',
  //   PoiCategory.viewpoint => 'Point de vue',
  //   PoiCategory.historic => 'Patrimoine',
  //   PoiCategory.beach => 'Plage / Lac',
  //   PoiCategory.boat => 'Port / Embarcadère',
  //   PoiCategory.warning => 'Danger',
  //   _ => 'Autre',
  // };
  // @override
  // IconData get icon => switch (this) {
  //   PoiCategory.start => Icons.play_arrow,
  //   PoiCategory.end => Icons.flag,
  //   PoiCategory.waypoint => Icons.circle,
  //   PoiCategory.water => Icons.water_drop,
  //   PoiCategory.food => Icons.restaurant,
  //   PoiCategory.repair => Icons.build,
  //   PoiCategory.shelter => Icons.house,
  //   PoiCategory.camping => Icons.terrain,
  //   PoiCategory.viewpoint => Icons.visibility,
  //   PoiCategory.historic => Icons.account_balance,
  //   PoiCategory.beach => Icons.beach_access,
  //   PoiCategory.boat => Icons.directions_boat,
  //   PoiCategory.warning => Icons.warning,
  //   _ => Icons.help_outline,
  // };
  // @override
  // Color get color => switch (this) {
  //   PoiCategory.start => Colors.green,
  //   PoiCategory.end => Colors.red,
  //   PoiCategory.waypoint => Colors.blue,
  //   PoiCategory.water => Colors.lightBlue,
  //   PoiCategory.food => Colors.orange,
  //   PoiCategory.repair => Colors.brown,
  //   PoiCategory.shelter => Colors.purple,
  //   PoiCategory.camping => Colors.teal,
  //   PoiCategory.viewpoint => Colors.indigo,
  //   PoiCategory.historic => Colors.deepOrange,
  //   PoiCategory.beach => Colors.cyan,
  //   PoiCategory.boat => Colors.blue,
  //   PoiCategory.warning => Colors.yellow,
  //   _ => Colors.grey,
  // };
}
