schema {
  query: DomainQuery
  mutation: Mutation
}

"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

"""Indicates an Input Object is a OneOf Input Object."""
directive @oneOf on INPUT_OBJECT

type AuthUserNode implements Node {
  email: String!
  username: String!
  password: String!

  """
  Designates that this user has all permissions without explicitly assigning them.
  """
  isSuperuser: Boolean!
  isStaff: Boolean!

  """The ID of the object"""
  id: ID!
}

type CountryType {
  code: String
  name: String
}

input CreateEtapeInput {
  voyageId: ID!
  titre: String
  description: String
  date: DateTime
  lng: Float!
  lat: Float!
  coverImage: Upload
  clientMutationId: String
}

type CreateEtapePayload {
  etape: EtapeNode
  clientMutationId: String
}

input CreateVoyageInput {
  titre: String
  description: String
  date: DateTime
  coverImage: Upload
  clientMutationId: String
}

type CreateVoyagePayload {
  voyage: VoyageNode
  clientMutationId: String
}

"""
The `DateTime` scalar type represents a DateTime
value as specified by
[iso8601](https://en.wikipedia.org/wiki/ISO_8601).
"""
scalar DateTime

input DeleteEtapeInput {
  etapeId: ID!
  clientMutationId: String
}

type DeleteEtapePayload {
  success: Boolean
  clientMutationId: String
}

input DeleteJSONWebTokenCookieInput {
  clientMutationId: String
}

type DeleteJSONWebTokenCookiePayload {
  deleted: Boolean!
  clientMutationId: String
}

input DeleteRefreshTokenCookieInput {
  clientMutationId: String
}

type DeleteRefreshTokenCookiePayload {
  deleted: Boolean!
  clientMutationId: String
}

input DeleteVoyageInput {
  voyageId: ID!
  clientMutationId: String
}

type DeleteVoyagePayload {
  success: Boolean
  clientMutationId: String
}

type DomainQuery {
  images: [ImageType]
  voyage(
    """The ID of the object"""
    id: ID!
  ): VoyageNode
  voyagesFilter(offset: Int, before: String, after: String, first: Int, last: Int, titre: String, description: String, date: DateTime): VoyageNodeConnection
  me: UserNode
  user(
    """The ID of the object"""
    id: ID!
  ): UserNode
  usersFilter(offset: Int, before: String, after: String, first: Int, last: Int, startsWith: String): UserNodeConnection
  userExists(email: String!): Boolean
  etape(
    """The ID of the object"""
    id: ID!
  ): EtapeNode
  countries: [CountryType]
}

"""An enumeration."""
enum DomainUserNationalityChoices {
  """Afghanistan"""
  AF

  """Åland Islands"""
  AX

  """Albania"""
  AL

  """Algeria"""
  DZ

  """American Samoa"""
  AS

  """Andorra"""
  AD

  """Angola"""
  AO

  """Anguilla"""
  AI

  """Antarctica"""
  AQ

  """Antigua and Barbuda"""
  AG

  """Argentina"""
  AR

  """Armenia"""
  AM

  """Aruba"""
  AW

  """Australia"""
  AU

  """Austria"""
  AT

  """Azerbaijan"""
  AZ

  """Bahamas"""
  BS

  """Bahrain"""
  BH

  """Bangladesh"""
  BD

  """Barbados"""
  BB

  """Belarus"""
  BY

  """Belgium"""
  BE

  """Belize"""
  BZ

  """Benin"""
  BJ

  """Bermuda"""
  BM

  """Bhutan"""
  BT

  """Bolivia"""
  BO

  """Bonaire, Sint Eustatius and Saba"""
  BQ

  """Bosnia and Herzegovina"""
  BA

  """Botswana"""
  BW

  """Bouvet Island"""
  BV

  """Brazil"""
  BR

  """British Indian Ocean Territory"""
  IO

  """Brunei"""
  BN

  """Bulgaria"""
  BG

  """Burkina Faso"""
  BF

  """Burundi"""
  BI

  """Cabo Verde"""
  CV

  """Cambodia"""
  KH

  """Cameroon"""
  CM

  """Canada"""
  CA

  """Cayman Islands"""
  KY

  """Central African Republic"""
  CF

  """Chad"""
  TD

  """Chile"""
  CL

  """China"""
  CN

  """Christmas Island"""
  CX

  """Cocos (Keeling) Islands"""
  CC

  """Colombia"""
  CO

  """Comoros"""
  KM

  """Congo"""
  CG

  """Congo (the Democratic Republic of the)"""
  CD

  """Cook Islands"""
  CK

  """Costa Rica"""
  CR

  """Côte d'Ivoire"""
  CI

  """Croatia"""
  HR

  """Cuba"""
  CU

  """Curaçao"""
  CW

  """Cyprus"""
  CY

  """Czechia"""
  CZ

  """Denmark"""
  DK

  """Djibouti"""
  DJ

  """Dominica"""
  DM

  """Dominican Republic"""
  DO

  """Ecuador"""
  EC

  """Egypt"""
  EG

  """El Salvador"""
  SV

  """Equatorial Guinea"""
  GQ

  """Eritrea"""
  ER

  """Estonia"""
  EE

  """Eswatini"""
  SZ

  """Ethiopia"""
  ET

  """Falkland Islands (Malvinas)"""
  FK

  """Faroe Islands"""
  FO

  """Fiji"""
  FJ

  """Finland"""
  FI

  """France"""
  FR

  """French Guiana"""
  GF

  """French Polynesia"""
  PF

  """French Southern Territories"""
  TF

  """Gabon"""
  GA

  """Gambia"""
  GM

  """Georgia"""
  GE

  """Germany"""
  DE

  """Ghana"""
  GH

  """Gibraltar"""
  GI

  """Greece"""
  GR

  """Greenland"""
  GL

  """Grenada"""
  GD

  """Guadeloupe"""
  GP

  """Guam"""
  GU

  """Guatemala"""
  GT

  """Guernsey"""
  GG

  """Guinea"""
  GN

  """Guinea-Bissau"""
  GW

  """Guyana"""
  GY

  """Haiti"""
  HT

  """Heard Island and McDonald Islands"""
  HM

  """Holy See"""
  VA

  """Honduras"""
  HN

  """Hong Kong"""
  HK

  """Hungary"""
  HU

  """Iceland"""
  IS

  """India"""
  IN

  """Indonesia"""
  ID

  """Iran"""
  IR

  """Iraq"""
  IQ

  """Ireland"""
  IE

  """Isle of Man"""
  IM

  """Israel"""
  IL

  """Italy"""
  IT

  """Jamaica"""
  JM

  """Japan"""
  JP

  """Jersey"""
  JE

  """Jordan"""
  JO

  """Kazakhstan"""
  KZ

  """Kenya"""
  KE

  """Kiribati"""
  KI

  """Kuwait"""
  KW

  """Kyrgyzstan"""
  KG

  """Laos"""
  LA

  """Latvia"""
  LV

  """Lebanon"""
  LB

  """Lesotho"""
  LS

  """Liberia"""
  LR

  """Libya"""
  LY

  """Liechtenstein"""
  LI

  """Lithuania"""
  LT

  """Luxembourg"""
  LU

  """Macao"""
  MO

  """Madagascar"""
  MG

  """Malawi"""
  MW

  """Malaysia"""
  MY

  """Maldives"""
  MV

  """Mali"""
  ML

  """Malta"""
  MT

  """Marshall Islands"""
  MH

  """Martinique"""
  MQ

  """Mauritania"""
  MR

  """Mauritius"""
  MU

  """Mayotte"""
  YT

  """Mexico"""
  MX

  """Micronesia"""
  FM

  """Moldova"""
  MD

  """Monaco"""
  MC

  """Mongolia"""
  MN

  """Montenegro"""
  ME

  """Montserrat"""
  MS

  """Morocco"""
  MA

  """Mozambique"""
  MZ

  """Myanmar"""
  MM

  """Namibia"""
  NA

  """Nauru"""
  NR

  """Nepal"""
  NP

  """Netherlands"""
  NL

  """New Caledonia"""
  NC

  """New Zealand"""
  NZ

  """Nicaragua"""
  NI

  """Niger"""
  NE

  """Nigeria"""
  NG

  """Niue"""
  NU

  """Norfolk Island"""
  NF

  """North Korea"""
  KP

  """North Macedonia"""
  MK

  """Northern Mariana Islands"""
  MP

  """Norway"""
  NO

  """Oman"""
  OM

  """Pakistan"""
  PK

  """Palau"""
  PW

  """Palestine, State of"""
  PS

  """Panama"""
  PA

  """Papua New Guinea"""
  PG

  """Paraguay"""
  PY

  """Peru"""
  PE

  """Philippines"""
  PH

  """Pitcairn"""
  PN

  """Poland"""
  PL

  """Portugal"""
  PT

  """Puerto Rico"""
  PR

  """Qatar"""
  QA

  """Réunion"""
  RE

  """Romania"""
  RO

  """Russia"""
  RU

  """Rwanda"""
  RW

  """Saint Barthélemy"""
  BL

  """Saint Helena, Ascension and Tristan da Cunha"""
  SH

  """Saint Kitts and Nevis"""
  KN

  """Saint Lucia"""
  LC

  """Saint Martin (French part)"""
  MF

  """Saint Pierre and Miquelon"""
  PM

  """Saint Vincent and the Grenadines"""
  VC

  """Samoa"""
  WS

  """San Marino"""
  SM

  """Sao Tome and Principe"""
  ST

  """Saudi Arabia"""
  SA

  """Senegal"""
  SN

  """Serbia"""
  RS

  """Seychelles"""
  SC

  """Sierra Leone"""
  SL

  """Singapore"""
  SG

  """Sint Maarten (Dutch part)"""
  SX

  """Slovakia"""
  SK

  """Slovenia"""
  SI

  """Solomon Islands"""
  SB

  """Somalia"""
  SO

  """South Africa"""
  ZA

  """South Georgia and the South Sandwich Islands"""
  GS

  """South Korea"""
  KR

  """South Sudan"""
  SS

  """Spain"""
  ES

  """Sri Lanka"""
  LK

  """Sudan"""
  SD

  """Suriname"""
  SR

  """Svalbard and Jan Mayen"""
  SJ

  """Sweden"""
  SE

  """Switzerland"""
  CH

  """Syria"""
  SY

  """Taiwan"""
  TW

  """Tajikistan"""
  TJ

  """Tanzania"""
  TZ

  """Thailand"""
  TH

  """Timor-Leste"""
  TL

  """Togo"""
  TG

  """Tokelau"""
  TK

  """Tonga"""
  TO

  """Trinidad and Tobago"""
  TT

  """Tunisia"""
  TN

  """Türkiye"""
  TR

  """Turkmenistan"""
  TM

  """Turks and Caicos Islands"""
  TC

  """Tuvalu"""
  TV

  """Uganda"""
  UG

  """Ukraine"""
  UA

  """United Arab Emirates"""
  AE

  """United Kingdom"""
  GB

  """United States Minor Outlying Islands"""
  UM

  """United States of America"""
  US

  """Uruguay"""
  UY

  """Uzbekistan"""
  UZ

  """Vanuatu"""
  VU

  """Venezuela"""
  VE

  """Vietnam"""
  VN

  """Virgin Islands (British)"""
  VG

  """Virgin Islands (U.S.)"""
  VI

  """Wallis and Futuna"""
  WF

  """Western Sahara"""
  EH

  """Yemen"""
  YE

  """Zambia"""
  ZM

  """Zimbabwe"""
  ZW
}

type EtapeNode implements Node {
  titre: String
  description: String
  ordre: Int!
  date: DateTime!

  """The ID of the object"""
  id: ID!
  lng: Float
  lat: Float
  coverImageUrl: String
}

"""
The `GenericScalar` scalar type represents a generic
GraphQL scalar value that could be:
String, Boolean, Int, Float, List or Object.
"""
scalar GenericScalar

type ImageType {
  title: String!
  image: String!
  createdAt: DateTime!
}

"""
Allows use of a JSON String for input / output from the GraphQL schema.

Use of this type is *not recommended* as you lose the benefits of having a defined, static
schema (one of the key benefits of GraphQL).
"""
scalar JSONString

input MutateEtapeInput {
  etapeId: ID!
  titre: String
  description: String
  lng: Float
  lat: Float
  coverImage: Upload
  removeImage: Boolean
  date: DateTime
  clientMutationId: String
}

type MutateEtapePayload {
  etape: EtapeNode
  clientMutationId: String
}

input MutateMeInput {
  bio: String
  image: Upload
  nationality: String
  removeImage: Boolean
  clientMutationId: String
}

"""Mutation Relay pour mettre à jour le profil de l'utilisateur connecté"""
type MutateMePayload {
  success: Boolean
  errors: JSONString
  user: UserNode
  clientMutationId: String
}

input MutateVoyageInput {
  voyageId: ID!
  titre: String
  description: String
  date: DateTime
  coverImage: Upload
  removeImage: Boolean
  clientMutationId: String
}

type MutateVoyagePayload {
  voyage: VoyageNode
  clientMutationId: String
}

type Mutation {
  uploadImage(image: Upload!, title: String!): UploadImage
  registerUser(input: RegisterUserInput!): RegisterUserPayload

  """Mutation Relay pour mettre à jour le profil de l'utilisateur connecté"""
  mutateMe(input: MutateMeInput!): MutateMePayload
  createVoyage(input: CreateVoyageInput!): CreateVoyagePayload
  mutateVoyage(input: MutateVoyageInput!): MutateVoyagePayload
  deleteVoyage(input: DeleteVoyageInput!): DeleteVoyagePayload
  createEtape(input: CreateEtapeInput!): CreateEtapePayload
  mutateEtape(input: MutateEtapeInput!): MutateEtapePayload
  deleteEtape(input: DeleteEtapeInput!): DeleteEtapePayload

  """Obtain JSON Web Token mutation"""
  tokenAuth(input: ObtainJSONWebTokenInput!): ObtainJSONWebTokenPayload
  verifyToken(input: VerifyInput!): VerifyPayload
  refreshToken(input: RefreshInput!): RefreshPayload
  deleteTokenCookie(input: DeleteJSONWebTokenCookieInput!): DeleteJSONWebTokenCookiePayload
  revokeToken(input: RevokeInput!): RevokePayload
  deleteRefreshTokenCookie(input: DeleteRefreshTokenCookieInput!): DeleteRefreshTokenCookiePayload
}

"""An object with an ID"""
interface Node {
  """The ID of the object"""
  id: ID!
}

input ObtainJSONWebTokenInput {
  clientMutationId: String
  email: String!
  password: String!
}

"""Obtain JSON Web Token mutation"""
type ObtainJSONWebTokenPayload {
  payload: GenericScalar!
  refreshExpiresIn: Int!
  clientMutationId: String
  token: String!
  refreshToken: String!
}

"""
The Relay compliant `PageInfo` type, containing data necessary to paginate this connection.
"""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

input RefreshInput {
  refreshToken: String
  clientMutationId: String
}

type RefreshPayload {
  payload: GenericScalar!
  refreshExpiresIn: Int!
  clientMutationId: String
  token: String!
  refreshToken: String!
}

input RegisterUserInput {
  email: String!
  username: String!
  password: String!
  confirmPassword: String!
  clientMutationId: String
}

type RegisterUserPayload {
  success: Boolean
  errors: JSONString
  token: String
  refreshToken: String
  user: AuthUserNode
  clientMutationId: String
}

input RevokeInput {
  refreshToken: String
  clientMutationId: String
}

type RevokePayload {
  revoked: Int!
  clientMutationId: String
}

"""
Create scalar that ignores normal serialization/deserialization, since
that will be handled by the multipart request spec
"""
scalar Upload

type UploadImage {
  image: ImageType
}

type UserNode implements Node {
  """The ID of the object"""
  id: ID!
  bio: String
  nationality: DomainUserNationalityChoices
  username: String
  email: String
  nationalityName: String
  imageUrl: String
  voyages(before: String, after: String, first: Int, last: Int): VoyageConnection
}

type UserNodeConnection {
  """Pagination data for this connection."""
  pageInfo: PageInfo!

  """Contains the nodes in this connection."""
  edges: [UserNodeEdge]!
}

"""A Relay edge containing a `UserNode` and its cursor."""
type UserNodeEdge {
  """The item at the end of the edge"""
  node: UserNode

  """A cursor for use in pagination"""
  cursor: String!
}

input VerifyInput {
  token: String
  clientMutationId: String
}

type VerifyPayload {
  payload: GenericScalar!
  clientMutationId: String
}

type VoyageConnection {
  """Pagination data for this connection."""
  pageInfo: PageInfo!

  """Contains the nodes in this connection."""
  edges: [VoyageEdge]!
}

"""A Relay edge containing a `Voyage` and its cursor."""
type VoyageEdge {
  """The item at the end of the edge"""
  node: VoyageNode

  """A cursor for use in pagination"""
  cursor: String!
}

type VoyageNode implements Node {
  titre: String!
  description: String!
  date: DateTime!

  """The ID of the object"""
  id: ID!
  etapes: [EtapeNode]
  owner: VoyageUserNode
  coverImageUrl: String
}

type VoyageNodeConnection {
  """Pagination data for this connection."""
  pageInfo: PageInfo!

  """Contains the nodes in this connection."""
  edges: [VoyageNodeEdge]!
}

"""A Relay edge containing a `VoyageNode` and its cursor."""
type VoyageNodeEdge {
  """The item at the end of the edge"""
  node: VoyageNode

  """A cursor for use in pagination"""
  cursor: String!
}

"""Version légère de UserNode sans voyages pour éviter les boucles"""
type VoyageUserNode implements Node {
  email: String!
  username: String

  """The ID of the object"""
  id: ID!
}

