"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

"""Indicates an Input Object is a OneOf Input Object."""
directive @oneOf on INPUT_OBJECT

input AttachFileInput {
  ownerType: OwnerTypeEnum!
  ownerId: ID!
  fileId: ID!
}

type CreateWaypointPayload {
  waypoint: WaypointType!
  vertex: VertexType!
}

"""Date (isoformat)"""
scalar Date

type FileAttachmentType {
  order: Int!
  isCover: Boolean!
  file: StoredFileType!
}

input ImageUploadRequest {
  filename: String!
  mimeType: String!
  size: Int!
}

type InsertVertexToSegmentPayload {
  segmentLeft: SegmentType!
  segmentRight: SegmentType!
}

input LatLngInput {
  lat: Float!
  lng: Float!
}

type LatLngType {
  lat: Float!
  lng: Float!
}

enum MobilityType {
  BIKE
  CAR
  BOAT
  WALK
  TRAIN
}

type Mutation {
  updateTrip(id: UUID!, trip: TripUpdateInput!): TripType!
  deleteTrip(id: UUID!): Boolean!
  createBlankTrip: TripType!
  updateWaypoint(id: UUID!, input: WaypointUpdateInput!): WaypointType!
  createBlankWaypointFromPosition(tripId: UUID!, latLng: LatLngInput!): CreateWaypointPayload!
  createBlankWaypointFromVertex(tripId: UUID!, vertexId: UUID!): CreateWaypointPayload!
  deleteWaypoint(id: UUID!): Boolean!
  insertVertexToSegment(vertexId: UUID!, segmentId: UUID!): InsertVertexToSegmentPayload!
  updateSegment(id: UUID!, input: SegmentUpdateInput!): SegmentType!
  createSegment(tripId: UUID!, input: SegmentCreateInput!): SegmentType!
  deleteSegment(id: UUID!): Boolean!
  moveVertex(id: UUID!, latLng: LatLngInput!): VertexType!
  createVertex(tripId: UUID!, latLng: LatLngInput!): VertexType!
  deleteVertex(id: UUID!): Boolean!
  detachFile(id: UUID!): Boolean!
  attachFile(input: AttachFileInput!): FileAttachmentType!
  generateImageUploadUrl(input: ImageUploadRequest!): UploadConfigType!
}

enum OwnerTypeEnum {
  TRIP
  WAYPOINT
}

enum PoiCategory {
  START
  END
  WAYPOINT
  WATER
  FOOD
  REPAIR
  SHELTER
  CAMPING
  VIEWPOINT
  HISTORIC
  BEACH
  BOAT
  WARNING
}

type Query {
  trip(id: UUID!): TripType!
  trips: [TripType!]!
}

input SegmentCreateInput {
  id: UUID
  mobilityType: MobilityType!
  startVertexId: UUID!
  endVertexId: UUID!
  geometry: [LatLngInput!]!
}

type SegmentType {
  id: UUID!
  mobilityType: MobilityType!
  startVertex: VertexType!
  endVertex: VertexType!
  geometry: [LatLngType!]!
}

input SegmentUpdateInput {
  geometry: [LatLngInput!]!
  mobilityType: MobilityType
  startVertexId: UUID
  endVertexId: UUID
}

type StoredFileType {
  id: UUID!
  filename: String!
  status: String!
  url: String!
}

type TopologyType {
  vertices: [VertexType!]!
  segments: [SegmentType!]!
}

type TripType {
  id: UUID!
  title: String!
  description: String!
  date: Date
  waypoints: [WaypointType!]!
  files: [FileAttachmentType!]!
  topology: TopologyType!
}

input TripUpdateInput {
  title: String
  description: String
  date: Date
}

type UploadConfigType {
  file: StoredFileType!
  uploadUrl: String!
  fileKey: String!
  contentType: String!
}

scalar UUID

type VertexType {
  id: UUID!
  latLng: LatLngType!
}

type WaypointType {
  id: UUID!
  title: String!
  description: String!
  poiCategory: PoiCategory!
  vertex: VertexType!
  files: [FileAttachmentType!]!
}

input WaypointUpdateInput {
  title: String
  poiCategory: PoiCategory
  vertexId: Int
  description: String
}

