#import "user_profile_fields.graphql"
mutation CreateProfile($profileName: String!) {
    createProfile(profileName: $profileName) {
        ... on CreateProfileSuccess {
            __typename
            profile {
                bio
            }
        }
        ... on UsernameAlreadyTaken {
            __typename
            message
        }
        ... on InvalidUsername {
            __typename
            message
        }
    }
}
mutation UpdateProfile($input: UpdateUserProfileInput!) {
    updateProfile(input: $input) {
        ...UserProfileFields
    }
}
