#import "image_fields.graphql"
mutation GenerateImageUploadUrl($filename: String!) {
    generateImageUploadUrl(filename: $filename) {
        fileKey
        uploadUrl
    }
}

mutation CreateImage($fileKey: String!) {
    createImage(data: { fileKey: $fileKey }) {
        ...ImageFields
    }
}
mutation DeleteImageFrom($id: Int!, $fileKey: String!, $type: OwnerType!) {
    deleteImageFrom(id: $id, fileKey: $fileKey, type: $type)
}

mutation AttachImageTo($id: Int!, $fileKey: String!, $type: OwnerType!) {
    attachImageTo(id: $id, fileKey: $fileKey, type: $type) {
        image {
            ...ImageFields
        }
    }
}
