name: domain_core
description: "Domain core for vamos cartographie"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  latlong2: ^0.9.1
  dartz: ^0.10.1
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  freezed_annotation: ^3.1.0
  equatable: ^2.0.8
  uuid: ^4.5.3
